#!/bin/bash

echo "🔨 Quick Rebuild - Apenas arquivos JSON atualizados"
echo ""
echo "✅ Correções aplicadas:"
echo "  1. Nó 'explain_code' agora TEM a opção 'Aceitar o Código Primordial'"
echo "  2. Nó 'explain_code' NÃO tem mais 'next' automático"
echo "  3. Ação 'give_item' movida do OPTION para o NÓ 'give_code'"
echo "  4. Item será adicionado ANTES da mensagem 'TRANSFERÊNCIA INICIADA'"
echo ""
echo "📋 Fluxo correto agora:"
echo "  1. START → 2 opções: 'O que é?' e 'Aceitar'"
echo "  2. Clica 'O que é?' → explain_code (explicação + opção 'Aceitar')"
echo "  3. Clica 'Aceitar' → give_code (adiciona item ANTES da mensagem)"
echo "  4. Mensagem 'TRANSFERÊNCIA INICIADA' aparece"
echo ""
echo "🔄 Para testar:"
echo "  1. Clique no botão 🔄 Recomeçar no jogo"
echo "  2. Ou faça Ctrl+Shift+R no navegador"
echo "  3. Inicie nova conversa com o Guia Ancião"
echo ""
echo "📊 Logs esperados no console:"
echo "  🔄 [DEBUG] Tem opções? 1  ← DEVE SER 1, NÃO 0!"
echo "  🔄 [DEBUG] Tem next? false ← DEVE SER FALSE!"
echo "  🎁 [DEBUG] ⚠️ PROCESSANDO GIVE_ITEM ANTES DO DIÁLOGO"
echo "  🎒 [DEBUG] Item adicionado com sucesso!"
echo ""
read -p "Pressione Enter para continuar com o build..."

npm run build

echo ""
echo "✅ Build completo!"
echo ""
echo "🚀 Próximos passos:"
echo "  1. Reinicie os containers: bash run-start-all-dev.sh"
echo "  2. Abra o jogo e clique em 🔄 Recomeçar"
echo "  3. Observe os logs no console (F12)"
